### PR TITLE
Convert integer to string

### LINKED ISSUE #11: Convert integer to string
Convert any 8-bit or 16-bit integer to a ASCII string.

- Ideas from https://ia600404.us.archive.org/3/items/Compute_s_Machine_Language_Routines_for_the_Commodore_64_and_128/Compute_s_Machine_Language_Routines_for_the_Commodore_64_and_128.pdf (page 130)

### PR DESCRIPTION
**Pull request by johnpalermo**
Fixes #11

### CODE REVIEW

**Comment by johnpalermo** [comment]
This is for 8-bit integers only, as 16-bit integer macro will come later. Will create new issue for 16-bit.

Testing results attached.

vice-screen-2023081920591464
vice-screen-2023081921015215

**Review by intoinside — COMMENTED** [review]
Needed to merge two test file in one, gradle plugin only recognize .spec.asm extension for test file.

**Comment by johnpalermo** [comment]
Thanks. Would be nice to introduce a screen pause to c128spec after every 25 rows and let user advance to next 25 lines by hitting any key. My tests were scrolling off the screen too fast and then I couldn't see them again. That's why I split my tests into 2 files and then didn't use gradle. Next time, I'll merge files back into one for gradle build. Thanks. 😊

**Comment by intoinside** [comment]
> Thanks. Would be nice to introduce a screen pause to c128spec after every 25 rows and let user advance to next 25 lines by hitting any key. My tests were scrolling off the screen too fast and then I couldn't see them again. That's why I split my tests into 2 files and then didn't use gradle. Next time, I'll merge files back into one for gradle build. Thanks. 😊

Yes this is a good point. Probably it's better to have an option to stop test suite in order to read results (like running test manually) or run all tests in unattended environment (gradle). 
I'll open a new issue con 128spec project.
Also Gradle could export detailed report after executing.... but this is another issue...
These are the only information on gradle... they could be improved
image

**Pull request merged**
